### ISSUE TITLE
Sonarr support?

### ISSUE THREAD

**Issue by karan** [Adman1020/Elsewherr#4]
Would be awesome to also add support for sonarr.

**Comment by Adman1020** [comment]
If you come across a service like Just Watch that can provide the same sort of information through an API but for shows (i.e. using something like tvdb ID), then adding Sonarr support should be fairly straight forward.

Unfortunately I've not come across a good API option for shows yet.

**Comment by Frooodle** [comment]
> If you come across a service like Just Watch that can provide the same sort of information through an API but for shows (i.e. using something like tvdb ID), then adding Sonarr support should be fairly straight forward.
> 
> Unfortunately I've not come across a good API option for shows yet.

I am actually in process of making a java version of this app as I thought you had abandoned this 
I have managed to get it working for sonarr and radarr
What I am using and found most reliable was actually using movie db for sonarr abd radarr as it supports both, so first getting its imdb ID searching that to get moviedb Id then like with radarr search that for providers (different endpoint though but same logic)

**Comment by Adman1020** [comment]
To be fair, I have basically abandoned it. But I'm picking it back up again now as I need to move to the newer version of Radarr.

Your logic sounds super clever for Sonarr, I will have a look at doing that.

**Comment by Frooodle** [comment]
Got a promotion at work so had to drop this for a bit, let me pick it back up this weekend.  Will let you know how it goes

**Comment by LiamAird** [comment]
I made a fork and made it work with Sonarr.
https://github.com/Adman1020/Elsewherr/pull/7
